### ISSUE TITLE
Add support for importing previous sales data to MailChimp

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-mail-chimp#1]
Using the new bulk processing in EDD 2.4, we should add a tool under the Tools tag for importing past sales data.

**Comment by cklosowski** [comment]
@pippinsplugins have a look over this

**Comment by pippinsplugins** [comment]
Aside from some PHPDoc clean up, looks great!

**Comment by pippinsplugins** [comment]
(oh and one inline comment about wpdb)

**Comment by pippinsplugins** [comment]
@cklosowski Could you finish this up early this week so we can ship it?

**Comment by cklosowski** [comment]
Yeah, it's working perfectly I'll formalize a commit.

**Comment by pippinsplugins** [comment]
@cklosowski What happens if you double import sales? Does MC detect duplicats?

**Comment by cklosowski** [comment]
it does detect duplicates. I've run the import on PPP multiple times now:
![screen shot 2015-08-05 at 9 33 57 am](https://cloud.githubusercontent.com/assets/1390124/9091448/3b971d7a-3b55-11e5-92ca-c46d252394fa.png)

**Comment by pippinsplugins** [comment]
Awesome, that's what I wanted to hear. Merge this in and deploy at will.
