### ISSUE TITLE
Update to API 3.0

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-mail-chimp#12]
MailChimp is discontinuing all previous versions of the API by the end of 2016: https://twitter.com/MailChimp_API/status/697843154616242176

**Comment by davekiss** [comment]
@pippinsplugins What's the general consensus on minimum supported PHP version for this? There's a nice lil API v3 wrapper for PHP 5.3+, but when I tried to move my own plugin to that about 3+ years ago, the world exploded due to namespacing.

**Comment by pippinsplugins** [comment]
5.3 is fine.

**Comment by davekiss** [comment]
Cool, thanks for the quick reply.

So, MailChimp switched some things up for the ways they manage subscribing an email to a list with associated interest categories (formerly called "Groups/Groupings"); namely, you can no longer subscribe an email to certain groups based on the group name, which is how it has been done in the past:

https://github.com/easydigitaldownloads/edd-mail-chimp/blob/92811288342f64e661546e2b76415394f8a88eab/includes/class-edd-mailchimp.php#L96

Instead, you must provide the ~~group~~ interest id, and a bool value if the user is to be associated with that interest [docs](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/)

I thought I'd bring this to light here and see if together we could come up with the best way of converting this stored data to a format that MailChimp will accept during subscription.

A couple of thoughts based on the code that currently exists:

- Write a raw (and somewhat nasty) SQL method that is fired on `init` to find downloads that have mailchimp settings with a `meta_key` of `edd_mailchimp` and _without_ a `converted_to_v3` meta key. 
- Make a MailChimp request to fetch the interest categories and interests for that list and compare the names to what is currently saved for that download's settings.
- Convert them to a new format that stores the `interest_id`, and add a `converted_to_v3` meta_key once the conversion has completed.

Any better ideas? @pippinsplugins @cklosowski

**Comment by pippinsplugins** [comment]
I think the best option would be to run an upgrade routine immediately after the plugin update is installed. EDD core provides an API for running batch upgrade routines that can reliably handle thousands of products. Have you seen that @davekiss ?

**Comment by davekiss** [comment]
@pippinsplugins can you link to the best place I can dive in and get learning?

**Comment by pippinsplugins** [comment]
Yep! https://github.com/easydigitaldownloads/Easy-Digital-Downloads/tree/master/includes/admin/upgrades

1. Add an admin notice with a link to start the upgrade routine. Example: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/upgrades/upgrade-functions.php#L134
2. Setup the upgrade routine itself: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/upgrades/upgrade-functions.php#L1050

**Comment by jprummer** [comment]
I'm not sure how far you all are on this but I started rebuilding this for the 3.0 API a few months ago and stopped because not all features were yet available in 3.0. I'm sure my code is a mess as I literally just stopped in the middle, but let me know if you want it. :)

**Comment by davekiss** [comment]
@jprummer thanks for the offer! I'm in the middle of rewriting a big chunk of this myself, so I'm guessing just sticking with what I've got will be quicker. I appreciate it!

**Comment by davekiss** [comment]
@pippinsplugins bit of a complication - the way that this plugin currently stores Group IDs makes it difficult to find the same record using API v3. You can no longer look up a Group record by its integer ID in API v3, so there is no surefire way of knowing that the Group that you are working with is the same one that is in the settings.

See the READ method here: http://developer.mailchimp.com/documentation/mailchimp/reference/lists/interest-categories/

The only thing that I can think of is to fetch all of the Groups/interest categories and loop through them to compare the name that you have stored for each individual interest with the name that MailChimp has on file. However, this doesn't ensure that it is the exact interest that we're looking for, as each Interest Category can have Interests with the same name. For example:

- Magazines
  - Reading
  - Writing
  - Editing

- Blogging
  - Reading
  - Writing
  - Editing

When you get a chance, have a look and let me know what you think we should do here.

**Comment by pippinsplugins** [comment]
That's unfortunate. Sounds like looping through and comparing names is probably the best way.

**Comment by davekiss** [comment]
Can you add me as a member here so I can start a new api3 branch?

**Comment by pippinsplugins** [comment]
Done.

**Comment by davekiss** [comment]
@pippinsplugins @cklosowski I'm in the middle of writing an upgrade routine and was planning on breaking away from the way that this plugin currently stores subscriber interests in the same post meta entry as the lists they should be subscribed to, eg:

            // array (size=5)
            //   0 => string '097846e40a' (length=10)
            //   1 => string '097846e40a|18033|Donating' (length=25)
            //   2 => string '097846e40a|18033|Events' (length=23)

The new thought was to have only `list_ids` in the `_edd_mailchimp` post meta and store subscriber interests in a `_edd_mailchimp_interests` post meta. However, it's looking like in order to do that, we'd need to refactor or override quite a few methods in the `EDD_Newsletter` class.

For example, this method doesn't provide any way for `subscribe_email` to know anything about the `download_id` to check for the list's related interests:

```php
	/**
	 * Check if a customer needs to be subscribed on completed purchase of specific products
	 */
	public function completed_download_purchase_signup( $download_id = 0, $payment_id = 0, $download_type = 'default' ) {

		$user_info = edd_get_payment_meta_user_info( $payment_id );
		$lists     = get_post_meta( $download_id, '_edd_' . $this->id, true );

		if( 'bundle' == $download_type ) {

			// Get the lists of all items included in the bundle

			$downloads = edd_get_bundled_products( $download_id );
			if( $downloads ) {
				foreach( $downloads as $d_id ) {
					$d_lists = get_post_meta( $d_id, '_edd_' . $this->id, true );
					if ( is_array( $d_lists ) ) {
						$lists = array_merge( $d_lists, (array) $lists );
					}
				}
			}
		}

		if( empty( $lists ) )
			return;

		$lists = array_unique( $lists );

		foreach( $lists as $list ) {
			$this->subscribe_email( $user_info, $list );
		}
	}
```

What's the status of this `EDD_Newsletter` class? Is it used by most other newsletter plugins? Was the plan to include it in EDD core similar to the `EDD_SL_Plugin_Updater` class? Will things break if this code is reworked?

I can either refactor, override several methods in the extending class, or, drop the idea entirely and keep going the old route. Thoughts?

**Comment by davekiss** [comment]
@pippinsplugins just to clarify, do you mean overridden (as in override from extending class), or rewritten?

**Comment by pippinsplugins** [comment]
Either is fine, take your pick.

Oh and see our Slack channel for some good news.

**Comment by pippinsplugins** [comment]
@davekiss this triggered unexpected output during activation:

The plugin generated 223 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by pippinsplugins** [comment]
Looks like it was due to this:

PHP Deprecated: Non-static method EDD_MailChimp_Extension::instance() should not be called statically in /Users/pippin/Sites/edd/wp-content/plugins/edd-mailchimp/edd-mailchimp.php on line 136

**Comment by pippinsplugins** [comment]
Fixed.

**Comment by pippinsplugins** [comment]
@davekiss I've tested this and it appears to work fine, but I'm pretty sure it's still running v2. I never saw an upgrade notice for v3. 

Doesn't look like any of the logic has been written to show site admins the upgrade notice. Is that correct?

**Comment by davekiss** [comment]
@pippinsplugins something must be amiss - the upgrade routine is written and should show a notice (see https://github.com/easydigitaldownloads/edd-mail-chimp/blob/api3/includes/class-edd-mailchimp-v3-upgrade.php)

**Comment by pippinsplugins** [comment]
Definitely didn't show :)

Could you test again please?

**Comment by davekiss** [comment]
@pippinsplugins the notice does show on my end. You can see [the class gets conditionally loaded here](https://github.com/easydigitaldownloads/edd-mail-chimp/blob/2dea51bf0f71c4497aaf38ebb1481576ab770fe4/edd-mailchimp.php#L61-L86)

Can you uncomment the dev code to ensure your EDD upgrade routines do not show that the routine has already been run?

**Comment by pippinsplugins** [comment]
@davekiss definitely does not show. I confirmed the upgrade routine is _not_ marked as completed.

**Comment by davekiss** [comment]
@pippinsplugins can you check if the [upgrade class is getting loaded here?](https://github.com/easydigitaldownloads/edd-mail-chimp/blob/api3/edd-mailchimp.php#L82)

**Comment by pippinsplugins** [comment]
I'll test in the morning and let you know.

**Comment by cklosowski** [comment]
Ok I got this installed, tested it with the upgrade routine. Other than the data looking the same within my list for the ecommerce data for a subscriber, should I see any difference?

I did verify that the ecommerce data for my other lists exists still.

**Comment by cklosowski** [comment]
Found a slight bug, maybe in the API3 stuff...but all my purchases are coming in at yesterday at 5pm (which would be UTC +0 today, based off my local timezone in Mailchimp)

![screen shot 2016-11-11 at 10 35 43 am](https://cloud.githubusercontent.com/assets/1390124/20224235/b8428856-a7fa-11e6-9cf2-2a5d02ac5881.png)

**Comment by davekiss** [comment]
@cklosowski this doesn't change ecommerce stuff at all yet - the first move is simply a transition to API3 calls for list subscribe and interest groupings

**Comment by flowdee** [comment]
do you think you can work it out during the next weeks? Shutdown of the old API coming closer 😨

**Comment by pippinsplugins** [comment]
It's on my priority list for next few weeks.

@flowdee the API isn't getting shut down on January 1 anymore. They extended it, hence our lack of urgency.

**Comment by danieliser** [comment]
Curious if this ever got finished? Would love to take advantage of all the new MC v3 Ecommerce automation goodies :)

**Comment by flowdee** [comment]
They are workin' on it as you can see here: https://github.com/easydigitaldownloads/edd-mail-chimp/pull/19#issuecomment-320323937

**Comment by pippinsplugins** [comment]
Moving over here from #19.

I've just tested a brand new site and list subscriptions are still not working here. Not yet sure why.

**Comment by pippinsplugins** [comment]
According to my MailChimp logs, there isn't a single PUT or POST request to the /members/ API endpoint.

I think it's failing because `$this->api` is not set in the `subscribe()` method of `EDD_MailChimp_List`.

**Comment by pippinsplugins** [comment]
Hmm, nope, definitely set.

**Comment by pippinsplugins** [comment]
I've been able to confirm that the subscribe() method of `EDD_MailChimp_List` works fine.

**Comment by pippinsplugins** [comment]
Ok pretty sure this is working now.

**Comment by pippinsplugins** [comment]
We need to send the `landing_site` parameter to MailChimp (it's not currently):
<img width="1312" alt="screen shot 2017-09-26 at 11 43 22 am" src="https://user-images.githubusercontent.com/1034109/30872519-fa09d450-a2af-11e7-9302-960453c320a3.png">

**Comment by pippinsplugins** [comment]
Upgrade notice won't ever go away for me:
<img width="1370" alt="screen shot 2017-09-26 at 11 53 32 am" src="https://user-images.githubusercontent.com/1034109/30872969-5a0a52a2-a2b1-11e7-8126-6a3c59865c06.png">

**Comment by pippinsplugins** [comment]
Here's another wrong thing:

<img width="1363" alt="screen shot 2017-09-26 at 11 58 08 am" src="https://user-images.githubusercontent.com/1034109/30873197-fed1b9a6-a2b1-11e7-86c2-53fb1f28258b.png">

It shows `Kyle ordered` when clearly it's on my `Pippin Williamson` profile.

**Comment by pippinsplugins** [comment]
Upgrade routine marked as complete successfully now.

**Comment by pippinsplugins** [comment]
Another todo: carts are not sent to MailChimp. Those need to be added so that cart recovery can be used.

**Comment by pippinsplugins** [comment]
Two new things I just found:

1. When activating MC on a brand new install, it shows a notice that the upgrade routine needs to run. This upgrade fails because there is no API key entered yet. It's also not needed because it's a fresh install.

2. We need to create the database tables during activation otherwise it throws PHP notices on initial activation.

**Comment by pippinsplugins** [comment]
Instead of removing orders from MailChimp, we need to mark them as refunded so that refunded email notifications can be sent.

**Comment by danieliser** [comment]
@pippinsplugins Been following your comments today, do you think its ready for testing on real data via staging & test MC list? I can run it later tonight and give you feedback on pass/fail & data sync.

**Comment by pippinsplugins** [comment]
@danieliser I would _love_ to have some testing :)

I would do it on a staging site though I don't believe there's anything "dangerous" with doing it on a live site.

**Comment by danieliser** [comment]
@pippinsplugins Awesome, super excited for this update so will definitely get this latest batch tested.

I did notice you referenced the debugger from EDD which I'm assuming is not in the current version. Any specific branch / commit I need for this to be compatible or will it work with the current version of EDD core as well?

**Comment by pippinsplugins** [comment]
@danieliser see https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4864

**Comment by sunnyratilal** [comment]
**First round of testing:**

- Upgrade routine notice doesn't seem to go away. On a fresh activation it still displays and doesn't go away even after the routine is run.  (API key has been entered). ⚠️ 
![image](https://user-images.githubusercontent.com/1525554/31007048-0e0a0a76-a4f7-11e7-8527-2274fdd5a398.png)
- List syncs correctly ✅ 
- After `Force Sync` is pressed, the page should redirect back to the `MailChimp Settings` but it redirects to the main settings page. ⚠️ 
- Purchasing with a new user account subscribes the user to the correct list and the order details are correctly passed to MailChimp ✅  (@pippinsplugins, I wasn't able to replicate [this](https://github.com/easydigitaldownloads/edd-mail-chimp/issues/12#issuecomment-332265379))

**Comment by cklosowski** [comment]
@pippinsplugins this is looking good. I'd like to see calls to `edd_debug_log` be wrapped in a function exists check. It's likely that b/c of the 3.0 upgrade people may try and upgrade MailChimp before EDD core, that way if they do, they don't get fatal errors.

**Comment by pippinsplugins** [comment]
@cklosowski there is a function_exists() fallback in `functions.php`:

```
if( ! function_exists( 'edd_debug_log' ) ) {
	function edd_debug_log( $message = '' ) {
		error_log( $message, 3,  trailingslashit( wp_upload_dir() ) . 'edd-debug-log.txt' );
	}
}
```

**Comment by mintplugins** [comment]
Here are a few of the initial issues I found while testing. Note that I am also going to be going through the docs to update them so I have a few questions about things as well:

- It wasn't clear what "Connecting a List" does or means - or even that I had to do something. Could the description of that setting be improved?

<img width="740" alt="screen shot 2017-10-02 at 12 15 08 pm" src="https://user-images.githubusercontent.com/1638128/31094836-5b8bfe5a-a76b-11e7-9635-e2ae1b69dc58.png">

- When disconnecting a list on the settings page I got this error:
```
Warning: rtrim() expects parameter 1 to be string, array given in /Users/philjohnston/Documents/wps/edd2.dev/wp-includes/formatting.php on line 2394

Warning: error_log(/edd-debug-log.txt): failed to open stream: Permission denied in /Users/philjohnston/Documents/wps/edd2.dev/wp-content/plugins/edd-mail-chimp/includes/functions.php on line 12

Warning: rtrim() expects parameter 1 to be string, array given in /Users/philjohnston/Documents/wps/edd2.dev/wp-includes/formatting.php on line 2394

Warning: error_log(/edd-debug-log.txt): failed to open stream: Permission denied in /Users/philjohnston/Documents/wps/edd2.dev/wp-content/plugins/edd-mail-chimp/includes/functions.php on line 12
```

- I get the same error as above when attempting to save a Product's list meta:
<img width="300" alt="screen shot 2017-10-02 at 12 23 22 pm" src="https://user-images.githubusercontent.com/1638128/31095118-8189064c-a76c-11e7-88ec-41ae1b77dae7.png">

**Comment by mintplugins** [comment]
Updating to EDD 2.7.8 resolved the warnings.

**Comment by mintplugins** [comment]
When checking out, even though I've checked the box to subscribe to the list, I am not actually subscribed to the list. I have confirmed that the list is checked for the product in question.

**Comment by pippinsplugins** [comment]
@mintplugins for the subscribe on checkout issue, was that with a brand new MC account or one that had been used with a store previously?

**Comment by mintplugins** [comment]
Also, my interest groups do not appear to be showing up on my product's edit screens:
<img width="300" alt="screen shot 2017-10-02 at 12 23 22 pm" src="https://user-images.githubusercontent.com/1638128/31100922-2d0b3f54-a780-11e7-8edf-99175f10554b.png">

Here they are in MailChimp:
<img width="1325" alt="screen shot 2017-10-02 at 2 44 33 pm" src="https://user-images.githubusercontent.com/1638128/31100940-448bcc84-a780-11e7-9151-5d0d97edbfd9.png">

**Comment by mintplugins** [comment]
@pippinsplugins For the subscribe on checkout, I am using a brand new account for testing at the moment.

**Comment by cklosowski** [comment]
On Initial activation (not having tested on this install yet) I see the following in Query Monitor:
<img width="1273" alt="screen shot 2017-10-03 at 8 53 31 am" src="https://user-images.githubusercontent.com/1390124/31126023-6adf106a-a818-11e7-913d-10abc0b9ffed.png">

This doesn't happen on page refresh because the tables exist now, but we should prevent those errors from occurring as they might raise some flags.

**Comment by cklosowski** [comment]
Notes on Testing:
- [x] The initial syncing seemed to work great. All the data was moved over in a reasonable amount of time
- [x] When a new email address was entered at checkout and opt'd in, the subscription to the list was completed
- [ ] When a new email address was entered at checkout but for an existing customer/user, ecommerce data was connected to this new email address.

**Comment by cklosowski** [comment]
Getting a weird situation with the upgrade routine.

This site never had MC on it before this 3.0 branch. My data was ported over fine but then today it started prompting me for an upgrade, and clicking it never completes, just keeps showing me that there is an upgrade in progress:
![screen shot 2017-10-03 at 12 12 39 pm](https://user-images.githubusercontent.com/1390124/31135903-8a6c2532-a834-11e7-900f-96c1eae8628e.png)

**Comment by cklosowski** [comment]
The URL on the upgrade link is:
`http://edd.dev/wp-admin/index.php?page=edd-upgrades&edd-upgrade=upgrade_mailchimp_api3`

**Comment by sunnyratilal** [comment]
I have the same as @cklosowski with the upgrade routines: clicking it never completes, just keeps showing me that there is an upgrade in progress.

**Comment by sunnyratilal** [comment]
@cklosowski I'm not sure if we can actually remove that error because it's baked into `dbDelta`: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/upgrade.php#L2218.

**Comment by cklosowski** [comment]
@sunnyratilal I know we've gotten around it in other extensions and EDD core before by checking if the table exists...does throwing an `@` before it stop it from outputting the error?

**Comment by pippinsplugins** [comment]
Just saw this PHP notice:

PHP Notice: Undefined index: price_id in /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-mailchimp/models/class-edd-mailchimp-order.php on line 92

**Comment by cklosowski** [comment]
There is a flaw in the way the upgrade routines are run. Because they redirect back onto each other automatically, notices aren't being cleared out prior to redirecting. Trying to clear it up now.

**Comment by sunnyratilal** [comment]
@cklosowski Yeah throwing the`@` removes the errors.

**Comment by cklosowski** [comment]
Lets do that then.

**Comment by cklosowski** [comment]
So i think i figured out the issue with the upgrade notices. I hadn't been running mailchimp on this environment prior to this so the setup was initially done via 3.0, however i'm not being prompted for the upgrade routine. I think we need to mark the 3.0 upgrade routines as complete on initial install.

**Comment by pippinsplugins** [comment]
@cklosowski we could check and see if the DB has any existing MC settings. If not settings, it's a new install.

**Comment by cklosowski** [comment]
Clicking force sync, redirects back to main extensions subsection instead of mailchimp subsection. Notice does show correctly though.

**Comment by cklosowski** [comment]
going to keep plugging away, having some issues with new orders getting added to MC ecommerce data for a user now.

**Comment by cklosowski** [comment]
Looks like my ecommerce data is just 'pending', even after clicking to force sync. probably why i'm missing some data?

<img width="1128" alt="screen shot 2017-10-06 at 11 47 32 am" src="https://user-images.githubusercontent.com/1390124/31286469-3843b360-aa8c-11e7-9618-956dbdc4c5d1.png">

**Comment by cklosowski** [comment]
Debug log shows that it's adding, so maybe we aren't catching a specific response and getting a false positive?
<img width="771" alt="screen shot 2017-10-06 at 12 00 26 pm" src="https://user-images.githubusercontent.com/1390124/31287043-01c68d74-aa8e-11e7-9c37-01f1696e2a75.png">

**Comment by pippinsplugins** [comment]
@cklosowski I think you're running into the same thing that I did. Everything pointed to it working, except the data not showing up in MailChimp.

**Comment by cklosowski** [comment]
Ok. I'll keep digging.

**Comment by cklosowski** [comment]
Looks like 'subscribe date' is getting a little mixed up too:
<img width="301" alt="screen shot 2017-10-06 at 5 07 33 pm" src="https://user-images.githubusercontent.com/1390124/31298614-f898a9dc-aab8-11e7-82a4-6acc6550c351.png">

**Comment by cklosowski** [comment]
Found the issue with commerce data not being sent:
<img width="771" alt="screen shot 2017-10-06 at 12 00 26 pm" src="https://user-images.githubusercontent.com/1390124/31299398-38fb7cd6-aabc-11e7-8a5c-813c9bd063dc.png">

**Comment by danieliser** [comment]
@cklosowski Does that mean that every product & variants has to be synced to the MC list prior to syncing purchases?

**Comment by cklosowski** [comment]
@danieliser still to be determined. I'm working through the debugging now.

**Comment by sunnyratilal** [comment]
@cklosowski Just pulled `master`, still getting the following notice:
`Easy Digital Downloads needs to complete a database upgrade that was previously started, click here to resume the upgrade.`

The other notice now doesn't show up as expected.

**Comment by cklosowski** [comment]
@sunnyratilal try `api3` branch? `Master` is not merged yet.

**Comment by cklosowski** [comment]
Also, you can kill that 'pending' upgrade thing in the `tools` section of EDD.

**Comment by sunnyratilal** [comment]
Sorry, meant `api3`

**Comment by sunnyratilal** [comment]
@cklosowski Whenever I'm running purchases, it's failing to send it to MailChimp:

```
2017-10-09 19:10:18 - add_order() MailChimp response error: The resource submitted could not be validated. For field-specific details, see the 'errors' array.
```

**Comment by cklosowski** [comment]
@sunnyratilal ok I've seen that error a few times too...could you try creating a new list, and setting it as the default, to see if that changes anything?

**Comment by sunnyratilal** [comment]
@cklosowski no luck, sadly

**Comment by sunnyratilal** [comment]
@cklosowski latest commit works a charm. Everyone is now working correctly.

**Comment by cklosowski** [comment]
**TESTING NOTE**

With these updates, you will need to re-save your downloads so that the details get re-sent about the product. This isn't going to be necessary in final release, just because we've been testing it and changed the way it was saved.

**Comment by sunnyratilal** [comment]
@cklosowski Further testing complete on other local sites and the data is being correctly to MailChimp.

**Comment by pippinsplugins** [comment]
@cklosowski @sunnyratilal do you guys feel this is ready for testing on a live site like pippinsplugins.com?

**Comment by sunnyratilal** [comment]
@pippinsplugins I've conducted more testing today and it seems to be consistent in the way it works now. Green light from me unless @cklosowski has been any weird issues today.

**Comment by danieliser** [comment]
@pippinsplugins Just ran this on staging with test list and it is still syncing data in the background I'm assuming as the list is getting updated with new non-subscribed customers, ecommerce purchase data and best of all the ecommerce campaigns are available. Will keep an eye on logs to see if any issues come up during background sync.

**Comment by cklosowski** [comment]
@pippinsplugins @sunnyratilal I think it's time to get it with some real data. In my testing everything is working as expected.

**Comment by pippinsplugins** [comment]
I'm going to put it on pippinsplugins.com then and start testing!

**Comment by pippinsplugins** [comment]
Here's a small bug:
![Uploading Screen Shot 2017-10-11 at 10.32.42 AM.png…]()
The group category names aren't showing, just the group names themselves.

**Comment by pippinsplugins** [comment]
Fixed.

**Comment by pippinsplugins** [comment]
Everything looks to be working! I did a test purchase and the order data immediately showed up in MC 🎉 !

**Comment by pippinsplugins** [comment]
Going to let it run for a day or two while keeping an eye on it.

**Comment by flowdee** [comment]
Regarding the meta box for lists and groups: 

Wouldn't there be a way collapse the list of groups below each list? This gets really ugly when you have more than 1 list in your mailchimp account with multiple groups.

**Comment by pippinsplugins** [comment]
A few sales have gone through and all looks well!

**Comment by pippinsplugins** [comment]
@flowdee it is collapsed automatically when the lists are unchecked.

**Comment by danieliser** [comment]
@pippinsplugins - After install am I supposed to see a global admin notice to perform some action? I know you were having trouble with it dismissing properly, but I just installed it on fresh copy of our live site which uses the current version and I didn't get any notices.

I can manually go into settings and select the list and force sync which works. Just wanted to be sure there wasn't supposed to be a message to upgrade.

**Comment by pippinsplugins** [comment]
@danieliser only if you had a default list and opt-in option enabled on checkout. If you didn't, you won't see an upgrade notice.

**Comment by mintplugins** [comment]
I was testing a different issue on a site where I hadn't configured MailChimp yet (settings are blank) and getting this upon checkout:

Notice: Trying to get property of non-object in /Users/philjohnston/Documents/wps/edd2.dev/wp-content/plugins/edd-mail-chimp/includes/class-edd-mailchimp-checkout.php on line 80

**Comment by danieliser** [comment]
@pippinsplugins Did have the optin on the checkout, not sure about setting a default list or not, but all seems to be working correctly except the date added for synced users is currently set to ```12/31/69 7:00PM```

**Comment by pippinsplugins** [comment]
@danieliser is that the date for newly added subscribers or subscribers that were added via the background sync?

**Comment by danieliser** [comment]
@pippinsplugins It appears for the background synced users who were not in the list already only.

**Comment by cklosowski** [comment]
@pippinsplugins I saw that too with users who were added via the background sync and not subscribed (Transactional users only)

**Comment by pippinsplugins** [comment]
I think the issue is due to us not passing the `processed_at_foreign` parameter, which MailChimp defines as: `The date and time the order was processed.`.

**Comment by pippinsplugins** [comment]
Scratch that, we do pass it.

**Comment by danieliser** [comment]
Just a heads up, was using the v3 test branch quite nicely until I updated the core plugin to the latest version via Dashboard -> Updates -> Manual update of edd core from wordpress.org.

Immediately white screened with 500 for missing EDD_Download class called from edd-mail-chimp which I am assuming means that the extension is calling that class for some reason during the update process while EDD core isn't technically available which then broke the update and required changing the edd-mail-chimp folder name then reactivating it which worked fine.

Just a heads up. May have been a one time glitch, idk. Working fine now though.

**Comment by danieliser** [comment]
@cklosowski I will check but don’t have high hopes as we Engine clears them every 24 hours.

From memory it was simply calling EDD_Download when it wasn’t available. I can attempt to break it on purpose today by deactivating core though I feel it would probably do it readily on a clean install. No syncing issues. Just error 500 until I got Edd-mail-chimp renamed and activated Edd core and them MC again.

**Comment by cklosowski** [comment]
No worries @danieliser, I've already pushed something to the branch that doesn't load up MC when the `Easy_Digital_Downloads` class is not present, that should fix it.

**Comment by cklosowski** [comment]
Ran into this when hitting the transaction failed page:
```
Warning	Invalid argument supplied for foreach()	1	wp-content/plugins/edd-mailchimp/models/class-edd-mailchimp-order.php:112	EDD_MailChimp_Order->_build()
wp-content/plugins/edd-mailchimp/models/class-edd-mailchimp-order.php:15
EDD_MailChimp_Order->__construct()
wp-content/plugins/edd-mailchimp/includes/class-edd-mailchimp-ecommerce.php:323
EDD_MailChimp_Ecommerce->cancel_order()
wp-includes/class-wp-hook.php:286
do_action('edd_update_payment_status')
wp-content/plugins/easy-digital-downloads/includes/payments/class-edd-payment.php:1745
EDD_Payment->update_status()
wp-content/plugins/easy-digital-downloads/includes/payments/class-edd-payment.php:859
EDD_Payment->save()
wp-content/plugins/easy-digital-downloads/includes/payments/functions.php:287
edd_update_payment_status()
wp-content/plugins/easy-digital-downloads/includes/checkout/functions.php:234
edd_listen_for_failed_payments()
wp-includes/class-wp-hook.php:286
do_action('template_redirect')
wp-includes/template-loader.php:12
```

**Comment by eugenesp** [comment]
When do you plan to release V3 for EDD customers?

**Comment by pippinsplugins** [comment]
Very, very soon. This week hopefully.

**Comment by cklosowski** [comment]
Just pushed up something for the order model that verifies that cart contents is an array and isn't empty to avoid the above scenario.

**Comment by pippinsplugins** [comment]
Merging this. Any and all bug reports can now be opened as new issues please.
