### ISSUE TITLE
Update to ECommerce360 v3

### ISSUE THREAD

**Issue by davekiss** [easydigitaldownloads/edd-mail-chimp#13]
According to my correspondence with Garvey at MailChimp, we need to figure out a significant routine to sync up order data with ECommerce360 v3, as the current v2 data model is incompatible with the new changes.

> In order to create new features for E-commerce360 (and prepare for future updates as well) our developers did a complete overhaul of that system. Because of this, there are currently two data models being used. 
> 
> In API v2.0, the 'Store' was just a string existing as part of the E-commerce Order object, and was not itself an object. in API v3.0, we've updated that so that E-commerce Stores can be created and modified separately from the calls to create new E-commerce Orders.
> 
> Because of this, there are significant limitations on what information from v2.0 can be found using v3.0. This is one of those limitations.
> 
> At this time our developers have not created a method of automatically converting from one data model to the other. As a result, the best way to convert the data is to use a v3.0 integration with the Ecommerce platform to re-sync the data entirely.
> 
> As for how existing data is handled, that is on a list-by-list basis. Lists will continue to use the v2.0 model as long as only v2.0 is used to insert orders. Using v3.0 to insert an order switches the data model to v3.0, which will make it so that the v2.0 data can still be seen using v2.0 API calls and in the subscriber profile and reports, but segmenting will only look for the v3.0 data.
> 
> I understand that this is a difficult and inconvenient change over, but we hope that with time the new data model will be able to provide much more powerful tools for Ecommerce users. In the meantime, I will reach out to developers, pass along your feedback, and see if it's at all possible to create any sort of resource for conversion from Ecommerce v2.0 into Ecommerce v3.0, in hopes that we can reduce the stress caused by this issue. Please let us know if you need any more assistance or have any further questions. We're always happy to help!

Opening this up here for further discussion.

**Comment by pippinsplugins** [comment]
Am I right in thinking that we could simply re-send all eCommerce data for all purchase records using the 3.0 model after installing the update?

**Comment by davekiss** [comment]
Right - there needs to be a mass import of purchase history. Just not sure how long that routine time might vary between sites. It ideally would be a background process because importing years of purchase data could run for quite a while, but how do you think it should be handled?

**Comment by cklosowski** [comment]
After talking with @davekiss at PN4, it might be beneficial to use a background processor (with no customer interaction) since the first big of V3 data that is sent will negate all V2 data. It's in our customer's best interest to get them to import all historical data into V3 as soon as possible, and I think a background process allows that without needing their interaction at all.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by davekiss** [comment]
Another note here - Ecommerce360 stores are now tied to specific lists. In order to add orders to a MailChimp store, you need to first create the store. When creating the store, you must provide a list ID parameter to define which list this store is associated with.

In the past, stores were global and were list-agnostic.

Perhaps we should loop through all of the lists in a mailchimp account and create an EDD store for each one? I'm not really sure what makes the most sense to do here :(

**Comment by pippinsplugins** [comment]
Can we have multiple stores per list?

Can we have multiple lists per store?

**Comment by cklosowski** [comment]
Wow, this is kind of a gamechanger in how it worked prior...

**Comment by davekiss** [comment]
@pippinsplugins I think the combination of the two (store_id + list_id) must be unique, and once created it operates as an individual entity

**Comment by pippinsplugins** [comment]
Blarg. That's so annoying.

**Comment by davekiss** [comment]
Please reference https://github.com/easydigitaldownloads/edd-mail-chimp/pull/19 for related progress on this generic issue.
