### ISSUE TITLE
Integrate MailChimp with Recurring

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-mail-chimp#14]
Idea Request:
Make it so that when a user purchases a recurring product, they get added to a corresponding list in MailChimp (EG "List for Product A"). 

When their subscription expires, they get removed (or moved to a different list).

**Comment by pippinsplugins** [comment]
I like this idea though I think instead of changing the list based on recurring status, we should simply send the subscription details through to MailChimp as merge tags.

**Comment by davekiss** [comment]
+1 on merge tags
