### ISSUE TITLE
Force refresh lists does not work anymore

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/edd-mail-chimp#16]
> To force refresh your lists, go to Downloads > Settings > Extensions and click Save Changes.

Not sure when it broke but it definitely does not work anymore.

**Comment by chriscct7** [comment]
Deleting the transient refreshes the lists correctly

**Comment by chriscct7** [comment]
Figured it out 
https://github.com/easydigitaldownloads/edd-mail-chimp/blob/7912117d3e2ba0c4722894825711609ddd138390/includes/class-edd-mailchimp.php#L24 is what Mailchimp is hooking into to refresh. It's a sanitization filter that is supposed to be backwards supported after sections:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/62f4ad4c0e95f86667cb2ab2687fcd3c770e154f/includes/admin/settings/register-settings.php#L911

That's where in EDD that should be firing, but because the extension now is on it's own section that's not going to fire off anymore.

**Comment by chriscct7** [comment]
This could arguably be an EDD regression. Some other extensions might assume that hook, like MailChimp does, will still fire even on their own sections.

**Comment by pippinsplugins** [comment]
We should try to fix this in core. At least two or three other newsletter plugins use the same setup.

**Comment by chriscct7** [comment]
Bare in mind that could potentially have negative consequences if extensions aren't expecting that ^. Not sure if there's any written that way, but its plausible some hook into both places so that whatever they're doing on the sanitize filter fires exactly once regardless if its before or after edd version with subsettings. If by fixing it you make it fire for those two, then anything hooked in there would fire twice

**Comment by davekiss** [comment]
This is being completely refactored in the `api3` branch, thought we'll continue hooking in to the `edd_settings_extensions_sanitize` filter in the case that the MailChimp extension is the first subsection listed in the Extensions tab (the `extensions` query string wouldn't be present in this case) or is the only Extension installed (unlikely but possible.)

**Comment by pippinsplugins** [comment]
:+1:
