### ISSUE TITLE
Support double opt-in on download specific lists

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-mail-chimp#17]
When using download specific list subscriptions, a user should be able to support double opt-in

**Comment by davekiss** [comment]
@pippinsplugins @cklosowski can you guys weigh in on the importance of this feature? Are you saying that it should be possible to mark double opt-in as not required globally, but required on any given individual download?

I'm still not really sure about how people use double opt-in anyway, so maybe I'm missing something.

**Comment by flowdee** [comment]
Here in Germany for example in most of the cases you are forced to use double opt-in. Right now I would not be able to use the download specific list feature because it doesn't make use of the global setting for "enable double opt-in".

**Comment by pippinsplugins** [comment]
>>>it should be possible to mark double opt-in as not required globally, but required on any given individual download?

Yes. It should be able to be configured for the checkout opt-in and also on a per-product basis for the automatic subscription added when purchasing a product.
