### ISSUE TITLE
Send price option to MailChimp

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/edd-mail-chimp#18]
It would be super useful to send the price option along to MailChimp when a customer purchases. For example, with AffiliateWP, we want to target users based on their license level (Professional, Ultimate etc). Currently we have to segment it based on price, but since there are upgrades, discount purchases etc, it's hard to know exactly what license level someone is on.

**Comment by SDavisMedia** [comment]
I have a customer of Free Downloads and MailChimp wanting to send data to MailChimp about which product was purchased through Free Downloads which resulted in being added to a MailChimp list. Would y'all consider this the same enhancement? If not, can create a new issue. 

Here's what he's actually requesting: 

```
First, I'm very satisfied with EDD. We use it with the MailChimp and Free Downloads extension. Which means lots of people sign up for our email list using the checkbox on the Free Downloads pop-up modal. But what would be really awesome is if that passed the download URL to MailChimp as the source of the signup so we could figure out how many people signed up as a result of that download.
```

**Comment by davekiss** [comment]
Product variants will be sent along with every order as part of the `api3` rewrite.

This feature has been implemented in the following commit: https://github.com/easydigitaldownloads/edd-mail-chimp/commit/7edd28ace09213dd48b515a0c48e155877163e52#diff-aa727cb93639db73e72cee58327f0998
