### ISSUE TITLE
Group Support

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/edd-mail-chimp#20]
Would be great to connect downloads (and options) with certain mailchimp group options.

![bildschirmfoto 2016-09-23 um 11 55 50](https://cloud.githubusercontent.com/assets/2278756/18782053/bdf306aa-8184-11e6-8d0d-0ee3b28433f0.png)

**Comment by pippinsplugins** [comment]
@flowdee we already support groups. They've been supported for a year+.

**Comment by flowdee** [comment]
Selecting groups for each download option as well? Sorry I mush have overseen this 😞
