### ISSUE TITLE
Updating/replacing existing groups

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/edd-mail-chimp#21]
Right now when someone is already subscribed to the list and buys another download which might be assigned to different groups, they are not being updated:
- Download 1: Group 1
- Download 2: Group 2, Group 3

After buying group 1 and being subscribed, he was assigned to group 1. But after buying Download 2 he is still assigned to group1 and not to 2 and 3 as well.

![bildschirmfoto 2016-09-24 um 11 57 44](https://cloud.githubusercontent.com/assets/2278756/18807691/22da80f6-824e-11e6-8304-eb5d76a5f241.png)

MC4WP solves this by an option to replace interest groups which is a very handy way.

**Problem**: Without updating/replacing the interest groups for example it's not possible to react on with automation triggers.

**Comment by davekiss** [comment]
I don't know that purchasing separate products warrants removing one interest and adding another, but new interests are merged with existing interests with the commit above.

**Comment by flowdee** [comment]
An additional option to overwrite would be perfect, but merging is fine in my case too.

**Comment by pippinsplugins** [comment]
An option to replace groups would be nice. I can see that being useful on sites that sell one or two products in a way that customers really only ever have one of them. For example, a site that sells one product at three different price points and they want a separate group for each product.

**Comment by flowdee** [comment]
on the point, thanks Pippin!

**Comment by flowdee** [comment]
Any chance to get #21 into your current rebuild as well? Would be awesome! 💚 @davekiss @brianhogg
