### ISSUE TITLE
updater should use item ID instead or item name

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-mail-chimp#22]
We need to be able to change the name of the EDD extension on the site. Instead of theme trickery, the extension itself should stop depending on the product name for updates. If it depends on ID instead, I can change the product name and resolve issues like: https://github.com/easydigitaldownloads/EDD-Site/issues/965

**Comment by pippinsplugins** [comment]
@cklosowski could you push this update tomorrow? Let's put this and only this into a point release.

**Comment by SDavisMedia** [comment]
Is this still feasible? Are the SL problems or anything in the way?

**Comment by pippinsplugins** [comment]
I believe we can do this now.

**Comment by cklosowski** [comment]
I think SL is all cleared up now. I'll get an update out for this, this week, in preparation for #12

**Comment by pippinsplugins** [comment]
Merged but moved to 3.0. That update is getting super close so we might as well combine them.
