### ISSUE TITLE
Send data to Mail Chimp feature shouldn't be enabled until account connected

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-mail-chimp#23]
The send sales data to Mail Chimp tool is awesome. But it can be confusing since it doesn't offer much feedback and can be submitted even when it does nothing. I think one simple improvement would be to prevent the tool from being used until a valid API key has been saved and a list selected in the settings.

**Comment by davekiss** [comment]
This tool is being replaced in the `api3` rewrite. Please see https://github.com/easydigitaldownloads/edd-mail-chimp/issues/26 for further discussion.
