### ISSUE TITLE
Return success or failure message on send sales data tool

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-mail-chimp#24]
That send sales data to Mail Chimp tool probably ought to show some kind of message after being submitted. Right now it can be submitted even though no account/list is connected as described in #23 and also without even specifying a date range...though that makes sense, maybe it should be visually indicated that selecting a date is optional? Anyway, regardless, after submission we should show a success or failure message so the user knows something actually happened.

**Comment by davekiss** [comment]
This tool is being reworked in the `api3` rewrite. Please see https://github.com/easydigitaldownloads/edd-mail-chimp/issues/26 for further discussion.
