### ISSUE TITLE
Checkout page checkbox & label alignment

### ISSUE THREAD

**Issue by pderksen** [easydigitaldownloads/edd-mail-chimp#5]
[This commit](https://github.com/easydigitaldownloads/edd-mail-chimp/commit/ce9368dc4e388a57c17fbaa1ca6803a6a3047e37) tweaked my checkbox/label alignment. I prefer <input> before <label>.

![image](https://cloud.githubusercontent.com/assets/79667/9279222/e488e29e-426a-11e5-9e5d-9454a63245d4.png)

I noticed EDD's checkout still has it the old way.

![image](https://cloud.githubusercontent.com/assets/79667/9279268/28261652-426b-11e5-8c07-92d75c226119.png)

Any suggested way to get it back? CSS? Filter?

**Comment by pippinsplugins** [comment]
This was done to make it consistent with core.

Can you look at the HTML and confirm the HTML matches (or doesn't match) now?

**Comment by pderksen** [comment]
@pippinsplugins Not sure what you mean.

https://easydigitaldownloads.com/checkout/ has <input> before <label> (for the mailchimp checkbox), and https://wpsimplepay.com/checkout/ has <label> before <input> (once you add to your cart of course).

Might just be a CSS tweak (though not sure what), but just curious why EDD's site has the HTML elements switched I guess.

**Comment by pderksen** [comment]
@pippinsplugins Looks like your site matches mine now.

![image](https://cloud.githubusercontent.com/assets/79667/9583198/c3f7af68-4fbe-11e5-830f-ff6703c08785.png)

**Comment by pippinsplugins** [comment]
Ok so CSS needs updated.

It now matches core HTML:

```
<p id="edd-email-wrap">
	<label class="edd-label" for="edd-email">
		<?php _e( 'Email Address', 'edd' ); ?>
		<?php if( edd_field_is_required( 'edd_email' ) ) { ?>
			<span class="edd-required-indicator">*</span>
		<?php } ?>
	</label>
	<span class="edd-description"><?php _e( 'We will send the purchase receipt to this address.', 'edd' ); ?></span>
	<input class="edd-input required" type="email" name="edd_email" placeholder="<?php _e( 'Email address', 'edd' ); ?>" id="edd-email" value="<?php echo esc_attr( $customer['email'] ); ?>"/>
</p>
```

**Comment by SDavisMedia** [comment]
@pippinsplugins I've reverted the changes that caused this. Everything's pushed and tagged 2.5.4. Just want to make sure the next step would be using Git Download Updater on the live site for pushing the update out.

**Comment by pippinsplugins** [comment]
Yes sir! Make sure change log doesn't get lost

**Comment by SDavisMedia** [comment]
@pippinsplugins Sweet. The update is pushed. The File Name field will not hold a value for some reason. http://glui.me/?i=r8bh07aex3o8jf5/2015-09-13_at_2.38_AM.png/ Folder name is good, though.

@pderksen Thanks for your patience here. Can you let me know if you have any issues with the automatic update? If everything goes well, this should align everything properly again without needing any additional CSS.

**Comment by pderksen** [comment]
@SDavisMedia @pippinsplugins Thanks, but it looks like the EDD-Mailchimp 2.5.3 add-on is still getting delivered in the automatic update. New zip file not pushed or version bump missed somewhere?

**Comment by SDavisMedia** [comment]
@pderksen How long ago did you try? If it was more than about 10 minutes ago, can you try for me one more time? Sorry for the inconvenience. We're trying to get a new updater system worked out.

**Comment by pderksen** [comment]
@SDavisMedia No problem. Just tried again and still updating to 2.5.3 with continued notification to update TO 2.5.4.

**Comment by SDavisMedia** [comment]
Okay thanks, man. I'll get it sorted out in just a few. I'll test on my own once I get another one taken care of. Feel free to just pull down `master` here.

Just out of curiosity, what's the name of your MailChimp plugin folder? *edd-mailchimp* or *edd-mail-chimp*?

**Comment by pderksen** [comment]
`edd-mailchimp` I don't mind being the guinea pig. :)

**Comment by SDavisMedia** [comment]
Thanks! Please give it a shot now and let me know if it works.

**Comment by pderksen** [comment]
No go still. Not sure if it matters but I'm on WP Engine.

**Comment by SDavisMedia** [comment]
No it shouldn't matter. There's something funky going on and I'm working with the guys right now to find some consistency in the issue. I'm sure we'll track it down shortly. Sorry about this!

**Comment by pderksen** [comment]
It's low priority. Don't sweat it. I'll test for you again later when you're ready.

**Comment by SDavisMedia** [comment]
Okay @pderksen! I think we're good to go now. You can give it a shot and if the universe loves me, you'll be running 2.5.4.

**Comment by pderksen** [comment]
Update worked...and fix worked. Thanks! :clap:

**Comment by SDavisMedia** [comment]
Thank you, Sir! I appreciate the patience and the testing. :+1:
