### ISSUE TITLE
Support for Checkout Fields Manager

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-mail-chimp#8]
Relevant ticket: https://secure.helpscout.net/conversation/157513499/24602/?folderId=321418

The goal is to be able to send data collected from the customer through fields created by Checkout Fields Manager to MailChimp like the other data is sent. That way MailChimp's features can be used with custom purchase data as well.

**Comment by davekiss** [comment]
@pippinsplugins In the `api3` branch, there is a filter added to the subscription payload that will allow other plugins to hook in and add their own `merge_vars`.

Think this sort of thing should be handled within the extension looking to add data (ie. Checkout Fields Manager, Software Licensing etc.), or, handled within the EDD_MailChimp `subscribe` method?

Related: https://github.com/easydigitaldownloads/edd-mail-chimp/issues/6

**Comment by pippinsplugins** [comment]
Awesome! I agree, the rest of this can be done through the other plugins.

**Comment by davekiss** [comment]
Sounds good. As a result, I'll be closing this issue along with #6 and #14
